---
version: "3"
services:
  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
        - ./torrc:/etc/tor/torrc:ro
    ports:
      - 8118:8118
      - 9050:9050
      - 9051:9051
    restart: unless-stopped
